FROM maven:3.6-jdk-8-slim as builder
RUN mkdir -p /build
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN mvn package

FROM openjdk:8-slim
EXPOSE 8080
ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
COPY --from=builder /build/target/Shop-0.0.1-SNAPSHOT.jar ksp3.jar
ENTRYPOINT ["java","-jar","ksp3.jar"]
